# Generated by Django 3.2.5 on 2021-11-24 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_coordinator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_trainee',
            field=models.BooleanField(default=True),
        ),
    ]
