# Generated by Django 3.2.5 on 2021-11-24 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUser', '0002_auto_20211124_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_believer',
            field=models.BooleanField(default=True),
        ),
    ]
