# Generated by Django 3.2.5 on 2021-11-24 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUser', '0003_user_is_believer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_believer',
            field=models.BooleanField(default=False),
        ),
    ]
