# Generated by Django 3.2.5 on 2021-11-24 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUser', '0004_alter_user_is_believer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_believer',
        ),
    ]
