# Generated by Django 3.2.5 on 2021-11-25 04:23

from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=profiles.models.handle_upload_profile_pic),
        ),
    ]
