# Generated by Django 3.2.5 on 2021-11-27 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_profile_avatar'),
        ('Coordinator', '0002_auto_20211125_0423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinator',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile'),
        ),
    ]
